#!/bin/sh
#
# Usage: mkcd <directory>
# Description: create a directory (including parents) and enter it
#

mkcd () {
  if [ -z "$1" ]; then
    echo "Usage: mkcd <directory>" 1>&2
    return 1
  fi

  mkdir -p -- "$1" && cd -- "$1"
}
