#!/bin/sh
#
# Usage: mkcd <directory>
# Description: create a directory (including parents) and enter it
#

mkcd () {
  if [ -z "$1" ]; then
    echo "Usage: mkcd <directory>" 1>&2
    return 1
  fi

  directory_path="${1%/}"
  if [ -z "$directory_path" ]; then
    directory_path="/"
  fi

  mkdir -p -- "$directory_path" && cd -- "$directory_path"
}
