cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'puma/puma'
tap 'caskroom/fonts'

brew 'ack'
brew 'ag'
brew 'coreutils'
brew 'git'
brew 'go'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'jq'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'puma/puma/puma-dev'
brew 'ruby-build'
brew 'rbenv'
brew 'reattach-to-user-namespace'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'tig'
brew 'tmux'
brew 'unrar'
brew 'vim'
brew 'wget'
brew 'yarn'
brew 'youtube-dl'

cask 'atom'
cask 'caffeine'
cask 'epoch-flip-clock'
cask 'firefox'
cask 'font-source-code-pro'
cask 'google-chrome'
cask 'handbrake'
cask 'hex-fiend'
cask 'imageoptim'
cask 'macdown'
cask 'postgres'
cask 'skype'
cask 'slack'
cask 'spectacle'
cask 'steam'
cask 'teamviewer'
cask 'tunnelbear'
cask 'virtualbox'
cask 'visual-studio-code'
cask 'vlc'
