# base16 color scheme (https://github.com/chriskempson/base16)
scheme: "Base"
author: "Paul Meinhardt (https://github.com/pmeinhardt)"
base00: "000000"
base01: "BF5345"
base02: "B7BC54"
base03: "FEBC68"
base04: "678C96"
base05: "B85776"
base06: "4C6F79"
base07: "C8C9CA"
base08: "505050"
base09: "DF645C"
base0A: "C1DB82"
base0B: "F7E577"
base0C: "6BABCA"
base0D: "CF6F95"
base0E: "6E848C"
base0F: "DDDDDD"
