#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

cd "$(dirname "$0")/.."

function has {
  command -v "$1" &> /dev/null
}

has ansible || brew install ansible

test -f config.yml || {
  echo "GitHub username:"
  read -er username
  echo "GitHub email:"
  read -er email
  printf "github:\n  username: \"%s\"\n  email: \"%s\"\n" "$username" "$email" > config.yml
}

ansible-playbook --extra-vars @config.yml --inventory hosts.yml macos.yml


exit 0

# If we're on a Mac, let's install and set up homebrew.
if [ "$(uname -s)" == "Darwin" ]
then
  info "installing dependencies"
  if source bin/dot | while read -r data; do info "$data"; done
  then
    success "dependencies installed"
  else
    fail "error installing dependencies"
  fi
fi

echo ''
echo '  All installed!'
