#!/usr/bin/env bash

set -o errexit

cd "$(dirname "$0")/.."
root=$(pwd -P)

# shellcheck source=./utils.sh
. ./script/utils.sh

macos () {
  test "$(uname -s)" = "Darwin"
}

user () {
  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

setup_gitconfig () {
  local -r src="$root/git/gitconfig.local.symlink.template"
  local -r dst="$root/git/gitconfig.local.symlink"

  local email=
  local name=
  local helper="cache"

  heading "Set up git configuration"

  if [ -f "$dst" ]; then
    warning "skipped, file exists: $dst"
  else
    if macos; then
      helper="osxkeychain"
    fi

    name=$(prompt "What is your GitHub handle?")
    email=$(prompt "What is your GitHub email?")

    sed \
      -e "s/AUTHORNAME/${name}/g" \
      -e "s/AUTHOREMAIL/${email}/g" \
      -e "s/GIT_CREDENTIAL_HELPER/${helper}/g" \
      "$src" > "$dst"

    success "created $dst"
  fi
}


link_file () {
  local -r src=$1
  local -r dst=$2

  local action=
  local backup=
  local overwrite=
  local skip=

  if [ -f "$dst" ] || [ -d "$dst" ] || [ -L "$dst" ]; then
    if [ "$(readlink "$dst")" == "$src" ]; then
      skip=true
    else
      info "file exists: $dst ($(basename "$src"))"

      printf "What do you want to do? [s]kip, [o]verwrite, [b]ackup"
      read -r -s -n 1 action
      printf "\n"

      case "$action" in
        "")
          skip=true;;
        b)
          backup=true;;
        o)
          overwrite=true;;
        s)
          skip=true;;
        *)
          ;;
      esac
    fi

    if [ "$overwrite" == "true" ]; then
      rm -rf "$dst"
      success "removed ${dst}"
    fi

    if [ "$backup" == "true" ]; then
      mv "$dst" "${dst}.backup"
      success "moved ${dst} → ${dst}.backup"
    fi

    if [ "$skip" == "true" ]; then
      warning "skipped ${src}"
    fi
  fi

  if [ "$skip" != "true" ]; then  # "false" or empty
    ln -s "$src" "$dst"
    success "linked $src → $dst"
  fi
}

install_dotfiles () {
  heading "Installing dotfiles"

  for src in $(find -H "$root" -maxdepth 2 -name '*.symlink' -not -path '*.git*'); do
    dst="$HOME/.$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done
}

setup_gitconfig
install_dotfiles

# If we're on a Mac, let's install and set up homebrew.
if [ "$(uname -s)" == "Darwin" ]
then
  info "installing dependencies"
  if source bin/dot | while read -r data; do info "$data"; done
  then
    success "dependencies installed"
  else
    fail "error installing dependencies"
  fi
fi

echo ''
echo '  All installed!'
