#!/usr/bin/env bash

# Run all dotfiles installers.

set -o errexit
set -o nounset
set -o pipefail

cd "$(dirname "$0")/.."

# Install Homebrew formulae from Brewfile
echo "› brew bundle"
brew bundle

# Find install scripts and run them iteratively
find . -name install.sh | while read -r installer; do
  echo "› ${installer#./}"
  sh -c "${installer}"
done

# find . -type d -name dot-dot | while read -r directory; do
#   if [ -x "$directory/configure" ]; then
#     sh -c "$directory/configure"
#   fi
#
#   if [ -x "$directory/install" ]; then
#     sh -c "$directory/install"
#   fi
# done
